### ISSUE TITLE
Running the contributed command:'extension.viewInBrowser' failed

### ISSUE THREAD

**Issue by mengesha1** [dai-shi/es-beautifier#13]
I can't able to use view in browser instead encounter the following problem:"Running the contributed command:'extension.viewInBrowser' failed" my os windows 10 ,visual studio code version 1.11.2

**Comment by dai-shi** [comment]
I'm afraid the error is coming from another extension.
Maybe this one? https://marketplace.visualstudio.com/items?itemName=qinjia.view-in-browser
