### ISSUE TITLE
highlight error

### ISSUE THREAD

**Issue by yoyo837** [dai-shi/es-beautifier#17]
![image](https://user-images.githubusercontent.com/6134547/43041879-e914040a-8d9f-11e8-8910-c83c23858c13.png)

At first I thought it was a problem with vscode, but when I try to disable this extension, the code highlights is work fine.

![image](https://user-images.githubusercontent.com/6134547/43041875-c61912b0-8d9f-11e8-8073-c6b009f1e77b.png)

**Comment by dai-shi** [comment]
Hi, thanks for reporting. Unfortunately, I wasn't able to reproduce the error, or I probably don't understand the issue. Nevertheless, I updated the extension (v1.1.0) with the latest dependencies. I may or may not fix the issue, but please git it a try.

**Comment by yoyo837** [comment]
@dai-shi Yes,He seems to be working fine, at least for now. If there are new situations, I will give feedback.

My screenshot failed to upload successfully due to network reasons, sorry for that.

**Comment by dai-shi** [comment]
Very good. Let me close this issue.
Feel free to reopen it if the problem persists, or open a new issue.
