### ISSUE TITLE
Benefit from vscode formatter API

### ISSUE THREAD

**Issue by jrieken** [dai-shi/es-beautifier#6]
VS Code has explicit API for registering formatters. Using that API has many benefits, like being integrated in the context menu by default, being part of "format on save" etc. We even wrote a blog post about it, explaining the (easy) changes and further benefits: http://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_the-formatting-api

Let me know if you need more information or a PR

**Comment by dai-shi** [comment]
Thanks @jrieken! I'll take a look at the doc.

**Comment by dai-shi** [comment]
@jrieken I tried to modify the code in ff009d8 referencing your blog. One of questions that arise to me is how can I use multiple formatters for a file type. Specifically, VSCode has its own JavaScript formatter, and I want to use both the own formatter and es-beautifier. Also, when I change a file type to es-beautifier, the syntax highlight is gone. This is maybe my configuration is wrong. Thanks for you help.

**Comment by jrieken** [comment]
There can only one formatter for a language - the details are explained here: http://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_multiple-formatters. If you need composition your formatter should expends the other formatter on a lower layer

**Comment by dai-shi** [comment]
Thanks for your comment. I understand there can be only one formatter, but still have some questions.

a) about the `"javascript.format.enable": true` configuration. should it be in the extension? I don't see it in https://github.com/jrieken/vscode-formatter-sample.

b) I still don't know how to enable syntax highlight that comes with VSCode, when the custom extension is effective. If you have any sample, it would be nice.

c) How do you like the idea of having both `registerDocumentFormattingEditProvider` and  `registerCommand` in the extension so that some user can use the format command without changing the default formatter, if they want.

**Comment by jrieken** [comment]
re a) Our JS formatter, that ships with VS Code and cannot be uninstalled, can be configured via the `javascript.format.enable`-setting. Extensions that offer multiple formatters or more than just formatting capabilities usually have settings as well. If an extension just does formatting, a setting isn't needed because a user can then just use that extension or uninstall it.

re b) how is syntax highlighting related to formatting?

re c) don't like, it will in inconsistent and user won't know what to do when

**Comment by dai-shi** [comment]
> re b) how is syntax highlighting related to formatting?

If I use the default formatter `javascript`, it show like this.

<img width="258" alt="image" src="https://cloud.githubusercontent.com/assets/490574/21207700/fa6525d2-c2ac-11e6-8a5c-96e163b674c8.png">

But, when I changed the formatter, by adding the following into settings.json,

```
{
    "files.associations": {"*.js":"es-beautifier"}
}
```

The syntax highlighting is gone like this.

<img width="237" alt="image" src="https://cloud.githubusercontent.com/assets/490574/21207742/3a91c570-c2ad-11e6-855c-ba13fa32d6e1.png">

Am I misunderstanding something?

**Comment by dai-shi** [comment]
I ended up with adding some configs from vscode in vendor dir (86214a0).

**Comment by dai-shi** [comment]
Just published v0.2.0 plugin.
